# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  commit_message:
    steps:
      - checkout
      - run:
          name: echo commit message
          command: |
            export COMMIT_MESSAGE=$(git log --format=oneline -n 1 ${CIRCLE_SHA1})
            echo World! and msg:  + $COMMIT_MESSAGE

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello"

  print_world:
    docker:
      -   image: circleci/node:13.8.0
    steps:
      - commit_message


workflows:
  say-hello-world-workflow:
    jobs:
      - print_hello
      - print_world:
          requires: [ print_hello ]
